// App-level domain types — NOT generated by Supabase CLI.
// These provide stronger typing for JSON columns stored in the database
// and for union types used throughout the app.

export interface TranscriptWord {
  start: number;
  end: number;
  text: string;
  confidence?: number;
}

export interface Segment {
  start: number;
  end: number;
  title: string;
  score: number;
}

export interface SubtitleSettings {
  fontName: string;
  fontSize: number;
  primaryColor: string;
  outlineColor: string;
  bold: boolean;
  outline: number;
  shadow: number;
  marginV: number;
  alignment: number;
}

export type VideoStatus = "uploaded" | "processing" | "completed" | "failed";

export type JobStatus =
  | "queued"
  | "extracting_audio"
  | "transcribing"
  | "detecting_segments"
  | "processing_video"
  | "burning_subtitles"
  | "uploading"
  | "completed"
  | "failed";

export type SubscriptionPlan = "free" | "starter" | "pro";

export type SubscriptionStatus =
  | "active"
  | "inactive"
  | "canceled"
  | "past_due"
  | "trialing";

/**
 * Maximum duration in seconds for generated shorts.
 * The AI chooses the natural duration for each passage;
 * this value acts as an upper bound.
 */
export type DurationOption = number;

/**
 * Duration filter options for the shorts display.
 * "all" shows every segment regardless of duration.
 */
export type DurationFilter = "7-15" | "15-30" | "30-60" | "all";
