// App-level domain types — NOT generated by Supabase CLI.
// These provide stronger typing for JSON columns stored in the database
// and for union types used throughout the app.

export interface TranscriptWord {
  start: number;
  end: number;
  text: string;
  confidence?: number;
}

export interface Segment {
  start: number;
  end: number;
  title: string;
  score: number;
}

export interface SubtitleSettings {
  fontName: string;
  fontSize: number;
  primaryColor: string;
  outlineColor: string;
  bold: boolean;
  outline: number;
  shadow: number;
  marginV: number;
  alignment: number;
}

export type VideoSource = "youtube" | "upload";

export type VideoStatus =
  | "uploaded"
  | "ready"
  | "processing"
  | "completed"
  | "failed";

export type ClipMode = "transcript_only" | "full_render";

export type JobStatus =
  | "queued"
  | "extracting_audio"
  | "transcribing"
  | "detecting_segments"
  | "processing_video"
  | "burning_subtitles"
  | "uploading"
  | "completed"
  | "failed";

export type SubscriptionPlan = "free" | "pro" | "business";

export type SubscriptionStatus =
  | "active"
  | "inactive"
  | "canceled"
  | "past_due"
  | "trialing";

/**
 * YouTube video metadata fetched via oEmbed / yt-dlp.
 */
export interface YouTubeMetadata {
  videoId: string;
  title: string;
  author: string;
  thumbnailUrl: string;
  /** Duration in seconds (0 if unknown) */
  duration: number;
}

/**
 * Referral record — tracks a user sharing for upload credit rewards.
 */
export interface Referral {
  id: string;
  referrer_id: string;
  platform: "twitter" | "other";
  credited: boolean;
  created_at: string;
}

/**
 * Maximum duration in seconds for generated shorts.
 * The AI chooses the natural duration for each passage;
 * this value acts as an upper bound.
 */
export type DurationOption = number;

/**
 * Duration filter options for the shorts display.
 * "all" shows every segment regardless of duration.
 */
export type DurationFilter = "7-15" | "15-30" | "30-60" | "all";
